import mongoose from "mongoose";

const formulaSchema = mongoose.Schema({
    nombre:{
        type:String,
        trim:true,
        required:true,
    },
    wattsInd:{
        type:Number,
        trim:true,
        required:true,
    },
    cantidad:{
        type:Number,
        trim:true,
        required:true,
    },
    wattsTotal:{
        type:Number,
        trim:true,
        required:true,
    },
    factorDemanda:{
        type:Number,
        trim:true,
        required:true,
    },
    factorDemandaVa:{
        type:Number,
        trim:true,
        required:true,
    },
    volts:{
        type:Number,
        trim:true,
        required:true,
    },
    vl:{
        type:Number,
        trim:true,
        required:true,
    },
    neutro:{
        type:Number,
        trim:true,
        required:true,
    },
    hilos:{
        type:Number,
        trim:true,
        required:true,
    },
    linea:{
        type:Number,
        trim:true,
        required:true,
    },
    iamps:{
        type:Number,
        trim:true,
        required:true,
    },
    vaP:{
        type:Number,
        trim:true,
        required:true,
    },
    amps:{
        type:Number,
        trim:true,
        required:true,
    },
    vaS:{
        type:Number,
        trim:true,
        required:true,
    },
    ft:{
        type:Number,
        trim:true,
        required:true,
    },
    fa:{
        type:Number,
        trim:true,
        required:true,
    },
    temperatura:{
        type:Number,
        trim:true,
        required:true,
    },
    tipoEquipo:{
        type: String,
        required:true,
        enum:['1', '2', '3'],
    },
    metodo1:{
       type:Number,
        trim:true,
        required:true,
    },
    metodo2:{
       type:Number,
        trim:true,
        required:true,
    },
    ampCorr:{
       type:Number,
        trim:true,
        required:true,
    },
    condCal:{
       type:Number,
        trim:true,
        required:true,
    },
    condTierra:{
        type:Number,
        trim:true,
        required:true,
    },
    hilosTierra:{
        type:Number,
        trim:true,
        required:true,
    },
    conductorNeutro:{
        type:Number,
        trim:true,
        required:true,
    },
    milimetrosTierra:{
        type:Number,
        trim:true,
        required:true,
    },
    totalMilimetros:{
        type:Number,
        trim:true,
        required:true,
    },
    canalizacion:{
       type:Number,
        trim:true,
        required:true,
    },
    caidaTension:{
        type:Number,
        trim:true,
        required:true,
    },
    porcentajeCaidaTension:{
        type:Number,
        trim:true,
        required:true,
    },
    cuadro:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Cuadro',
    },
},
    {
        timestamps:true

})

const Formula = mongoose.model('Formula', formulaSchema)
export default Formula